telegram:
  bot:
    username: communitystagebot
    token: 7483072284:AAEKReYVUKfbCu8i1kQHZW7IuV_W-ejMkCY

community:
  likes-queue: like-events
  payment-queue: payment-events

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

spring:
  app:
    rabbit:
      like-event-queue-name: like-events
      payment-event-queue-name: payment-events
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydatabase
      username: admin
      password: admin123
    redis:
      url: redis://redis:6379
  datasource:
    url: jdbc:postgresql://db:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  rabbitmq:
    username: ${RABBIT_USER}
    password: ${RABBIT_USER}

amazon:
  s3:
    access-key: .
    secret-key: .
    bucket-name: .

logging:
  level:
    root: info
  file:
    name: logs/community.log
server:
  port: 8080

paypal:
  client:
    id: .
    secret: .
    mode: sandbox