telegram:
  bot:
    username: username
    token: token

spring:
  data:
    redis:
      url: redis://localhost:6379

amazon:
  s3:
    access-key: access_key
    secret-key: secret_key
    bucket-name: bucket_name

logging:
  level:
    root: info