telegram:
  bot:
    username: none
    token: none

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydatabase
      username: admin
      password: admin123

amazon:
  s3:
    access-key: none
    secret-key: none
    bucket-name: none