telegram:
  bot:
    username: commulinkbot
    token: 6347574819:AAEOj937arRXFI78W44aFfAaw0qvmrj9v-M

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydatabase
      username: admin
      password: admin123

amazon:
  s3:
    access-key: AKIASLAHI4MVD2Z4ZSOT
    secret-key: 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
    bucket-name: commulinkdata