telegram:
  bot:
    username: username
    token: token

spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      host: mongodb
      port: 27017
      database: data
    redis:
      url: redis://localhost:6379

amazon:
  s3:
    access-key: access_key
    secret-key: secret_key
    bucket-name: bucket_name

logging:
  level:
    root: info