telegram:
  bot:
    username: .
    token: .

community:
  likes-queue: like-events
  payment-queue: payment-events

spring:
  app:
    rabbit:
      like-event-queue-name: like-events
      payment-event-queue-name: payment-events
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydatabase
      username: admin
      password: admin123
    redis:
      url: redis://localhost:6379
  datasource:
    url: jdbc:postgresql://localhost:5432/community
    username: postgres
    password: postgres
  rabbitmq:
    username: alex
    password: alex

amazon:
  s3:
    access-key: .
    secret-key: .
    bucket-name: .

logging:
  level:
    root: info
server:
  port: 8080

paypal:
  client:
    id: .
    secret: .
    mode: sandbox